-- Seed some baseline rows so the optimizer considers index merge plans.
-- The reproduction script inserts the MVCC-invisible rows separately.

INSERT INTO calendar_events
  (eie, status, start_date, start_time, end_date, end_time,
   timezone, title, event_type, staff_id, sfname, slname,
   inquiry_id, groupclients)
SELECT
  0, 'active',
  DATE_ADD('2026-01-01', INTERVAL FLOOR(RAND(n)*365) DAY),
  SEC_TO_TIME(FLOOR(RAND(n+1)*86400)),
  DATE_ADD('2026-01-01', INTERVAL FLOOR(RAND(n+2)*365) DAY),
  SEC_TO_TIME(FLOOR(RAND(n+3)*86400)),
  'America/New_York',
  CONCAT('Event ', n),
  'meeting',
  FLOOR(RAND(n+4)*100),
  'John', 'Doe',
  FLOOR(RAND(n+5)*50000),
  JSON_ARRAY(FLOOR(RAND(n+6)*50000), FLOOR(RAND(n+7)*50000))
FROM (
  SELECT a.N + b.N*10 + c.N*100 + d.N*1000 + e.N*10000 + f.N*100000 AS n
  FROM
    (SELECT 0 N UNION SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4
     UNION SELECT 5 UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9) a,
    (SELECT 0 N UNION SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4
     UNION SELECT 5 UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9) b,
    (SELECT 0 N UNION SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4
     UNION SELECT 5 UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9) c,
    (SELECT 0 N UNION SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4
     UNION SELECT 5 UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9) d,
    (SELECT 0 N UNION SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4
     UNION SELECT 5 UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9) e,
    (SELECT 0 N UNION SELECT 1) f
) nums;
